/*###### PostgreSQL ######*/
create table purchase (
	id int8 generated by default as identity,
	subscriber_id int8 not null,
	timestamp int8 not null,
	created_at timestamp,
	updated_at timestamp,
	primary key (id)
)

create table subscriber (
	id int8 generated by default as identity,
	msisdn int8 not null,
	created_at timestamp,
	updated_at timestamp,
	primary key (id)
)

create table subscription (
	id int8 generated by default as identity,
	created_at timestamp,
	updated_at timestamp,
	timestamp int8 not null,
	subscriber_id int8 not null,
	primary key (id)
)

alter table if exists subscriber add constraint unique_subscriber_msisdn unique (msisdn)
alter table if exists purchase add constraint fk_purchase_subscriber foreign key (subscriber_id) references subscriber
alter table if exists subscription add constraint fk_subscription_subscriber foreign key (subscriber_id) references subscriber

/*
#### MySQL ####

create table purchase (
	id bigint not null auto_increment,
	subscriber_id bigint not null,
	timestamp bigint not null,
	created_at datetime(6),
	updated_at datetime(6),
	primary key (id)
) engine=InnoDB;

create table subscriber (
	id bigint not null auto_increment,
	msisdn bigint not null,
	created_at datetime(6),
	updated_at datetime(6),
	primary key (id)
) engine=InnoDB;

create table subscription (
	id bigint not null auto_increment,
	subscriber_id bigint not null,
	timestamp bigint not null,
	created_at datetime(6),
	updated_at datetime(6),
	primary key (id)
) engine=InnoDB;

alter table subscriber add constraint msisdn_unique unique (msisdn);
alter table purchase add constraint fk_purchase_subscriber foreign key (subscriber_id) references subscriber (id);
alter table subscription add constraint fk_subscription_subscriber foreign key (subscriber_id) references subscriber (id);
*/
